tests = [ {'description': 'Full Fuel',
    'steps': [ {'inputs': [('PINA',0x0F)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x3F)],
    },
    {'description': '13 Fuel',
    'steps': [ {'inputs': [('PINA',0x0D)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x3F)],
    },
    {'description': '11 Fuel',
    'steps': [ {'inputs': [('PINA',0x0B)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x3E)],
    },
    {'description': '9 Fuel',
    'steps': [ {'inputs': [('PINA',0x09)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x3C)],
    },
    {'description': '5 Fuel',
    'steps': [ {'inputs': [('PINA',0x05)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x38)],
    },
    {'description': '4 Fuel (Low Fuel)',
    'steps': [ {'inputs': [('PINA',0x04)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x70)],
    },
    {'description': '3 Fuel (Low Fuel)',
    'steps': [ {'inputs': [('PINA',0x03)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x70)],
    },
    {'description': '1 Fuel (Low Fuel)',
    'steps': [ {'inputs': [('PINA',0x01)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x60)],
    },
    {'description': 'No Fuel (Low Fuel)',
    'steps': [ {'inputs': [('PINA',0x00)], 'iterations': 5 } ],
    'expected': [('PORTC', 0x40)],
    },
    ]
#watch = ['PORTB']

