tests = [ {'description': '0x00 and 0x00 -> 0',
    'steps': [ {'inputs': [('PINA',0x00), ('PINB',0x00)], 'iterations': 5 } ],
    'expected': [('PORTC', 0)],
    },
    {'description': '0xFF and 0x00 -> 8',
    'steps': [ {'inputs': [('PINA',0xFF), ('PINB',0x00)], 'iterations': 5 } ],
    'expected': [('PORTC', 8)],
    },
    {'description': '0x00 and 0xFF -> 8',
    'steps': [ {'inputs': [('PINA',0x00), ('PINB',0xFF)], 'iterations': 5 } ],
    'expected': [('PORTC', 8)],
    },
    {'description': '0xFF and 0xFF -> 16',
    'steps': [ {'inputs': [('PINA',0xFF), ('PINB',0xFF)], 'iterations': 5 } ],
    'expected': [('PORTC', 16)],
    },
    {'description': '0x0F and 0xF0 -> 8',
    'steps': [ {'inputs': [('PINA',0x0F), ('PINB',0xF0)], 'iterations': 5 } ],
    'expected': [('PORTC', 8)],
    },
    {'description': '0x10 and 0x04 -> 2',
    'steps': [ {'inputs': [('PINA',0x10), ('PINB',0x04)], 'iterations': 5 } ],
    'expected': [('PORTC', 2)],
    },
    ]
#watch = ['PORTB']

